// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StageFlowVag.Repository;

#nullable disable

namespace StageFlowVag.Repository.Migrations
{
    [DbContext(typeof(StageFlowVagDbContext))]
    [Migration("20251108050821_initial_create")]
    partial class initial_create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<int>("CoordenadorId")
                        .HasColumnType("integer")
                        .HasColumnName("coordenador_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CursoVinculado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("curso_vinculado");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("EmailCoordenador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_coordenador");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("local");

                    b.Property<string>("NomeCoordenador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_coordenador");

                    b.Property<string>("ObservacoesGerais")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes_gerais");

                    b.Property<int>("PublicoEstimado")
                        .HasColumnType("integer")
                        .HasColumnName("publico_estimado");

                    b.Property<bool>("RequerCerimonial")
                        .HasColumnType("boolean")
                        .HasColumnName("requer_cerimonial");

                    b.Property<bool>("RequerDivulgacao")
                        .HasColumnType("boolean")
                        .HasColumnName("requer_divulgacao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_evento");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CoordenadorId")
                        .HasDatabaseName("idx_eventos_coordenador");

                    b.HasIndex("DataInicio")
                        .HasDatabaseName("idx_eventos_data_inicio");

                    b.HasIndex("Local")
                        .HasDatabaseName("idx_eventos_local");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_eventos_status");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.RecursoAudioVisual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("NumeroPatrimonio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_patrimonio");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_disponivel");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("NumeroPatrimonio")
                        .HasDatabaseName("idx_recursos_patrimonio");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_recursos_status");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("idx_recursos_tipo");

                    b.ToTable("recurso_audiovisual", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.ReservaRecurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataHoraDevolucao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_devolucao");

                    b.Property<DateTime?>("DataHoraEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_entrega");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_fim");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer")
                        .HasColumnName("evento_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ObservacoesReserva")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes_reserva");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer")
                        .HasColumnName("recurso_id");

                    b.Property<string>("ResponsavelDevolucao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("responsavel_devolucao");

                    b.Property<string>("ResponsavelEntrega")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("responsavel_entrega");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("idx_reservas_evento");

                    b.HasIndex("RecursoId")
                        .HasDatabaseName("idx_reservas_recurso");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_reservas_status");

                    b.HasIndex("DataHoraInicio", "DataHoraFim")
                        .HasDatabaseName("idx_reservas_periodo");

                    b.ToTable("reserva_recurso", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<DateTime?>("DataLimite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_limite");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer")
                        .HasColumnName("evento_id");

                    b.Property<bool>("GeradoAutomaticamente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("gerado_automaticamente");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ObservacoesConclusao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes_conclusao");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer")
                        .HasColumnName("prioridade");

                    b.Property<string>("ResponsavelNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("responsavel_nome");

                    b.Property<int>("SetorResponsavel")
                        .HasColumnType("integer")
                        .HasColumnName("setor_responsavel");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("DataLimite")
                        .HasDatabaseName("idx_checklist_data_limite");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("idx_checklist_evento");

                    b.HasIndex("SetorResponsavel")
                        .HasDatabaseName("idx_checklist_setor");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_checklist_status");

                    b.ToTable("checklist_item", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.ReservaRecurso", b =>
                {
                    b.HasOne("StageFlowVag.Domain.Entities.Audiovisual.Evento", "Evento")
                        .WithMany("RecursosReservados")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageFlowVag.Domain.Entities.Audiovisual.RecursoAudioVisual", "Recurso")
                        .WithMany("Reservas")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.ChecklistItem", b =>
                {
                    b.HasOne("StageFlowVag.Domain.Entities.Audiovisual.Evento", "Evento")
                        .WithMany("Checklist")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.Evento", b =>
                {
                    b.Navigation("Checklist");

                    b.Navigation("RecursosReservados");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.RecursoAudioVisual", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
