// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StageFlowVag.Repository;

#nullable disable

namespace StageFlowVag.Repository.Migrations
{
    [DbContext(typeof(StageFlowVagDbContext))]
    [Migration("20251108084258_novos_campos_solicitacao")]
    partial class novos_campos_solicitacao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StageFlowVag.Domain.Entities.AtendimentosDepartamentos.AtendimentoDepartamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<int>("Departamento")
                        .HasColumnType("integer")
                        .HasColumnName("departamento");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer")
                        .HasColumnName("responsavel_id");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitacao_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Departamento")
                        .HasDatabaseName("idx_atendimento_departamento");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("SolicitacaoId")
                        .HasDatabaseName("idx_atendimento_solicitacao");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_atendimento_status");

                    b.ToTable("atendimento_departamento", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Blocos.Bloco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("idx_blocos_nome");

                    b.ToTable("blocos", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Blocos.DisponibilidadeBloco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<int>("BlocoId")
                        .HasColumnType("integer")
                        .HasColumnName("bloco_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_fim");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<int?>("SolicitacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitacao_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BlocoId")
                        .HasDatabaseName("idx_disponibilidade_bloco");

                    b.HasIndex("SolicitacaoId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_disponibilidade_status");

                    b.HasIndex("DataHoraInicio", "DataHoraFim")
                        .HasDatabaseName("idx_disponibilidade_periodo");

                    b.ToTable("disponibilidade_blocos", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Insumos.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Departamento")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Solicitacoes.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<bool?>("Aprovado")
                        .HasColumnType("boolean")
                        .HasColumnName("aprovado");

                    b.Property<int?>("AprovadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("aprovado_por_id");

                    b.Property<int?>("BlocoId")
                        .HasColumnType("integer")
                        .HasColumnName("bloco_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aprovacao");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_evento");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_fim");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JustificativaRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("justificativa_rejeicao");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("local");

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_evento");

                    b.Property<string>("NomeSolicitante")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeSocilitante");

                    b.Property<int>("PublicoEstimado")
                        .HasColumnType("integer")
                        .HasColumnName("publico_estimado");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitante_id");

                    b.HasKey("Id");

                    b.HasIndex("Aprovado")
                        .HasDatabaseName("idx_solicitacoes_aprovado");

                    b.HasIndex("BlocoId")
                        .HasDatabaseName("idx_solicitacoes_bloco");

                    b.HasIndex("DataEvento")
                        .HasDatabaseName("idx_solicitacoes_data");

                    b.HasIndex("SolicitanteId")
                        .HasDatabaseName("idx_solicitacoes_solicitante");

                    b.ToTable("solicitacoes", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Solicitacoes.SolicitacoesInsumos.SolicitacaoInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("SolicitacaoInsumos");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Departamento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matricula");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_usuarios_email");

                    b.HasIndex("Matricula")
                        .IsUnique()
                        .HasDatabaseName("idx_usuarios_matricula");

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_usuarios_role");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.AtendimentosDepartamentos.AtendimentoDepartamento", b =>
                {
                    b.HasOne("StageFlowVag.Domain.Entities.Usuarios.Usuario", "Responsavel")
                        .WithMany("Atendimentos")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StageFlowVag.Domain.Entities.Solicitacoes.Solicitacao", "Solicitacao")
                        .WithMany("Atendimentos")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Blocos.DisponibilidadeBloco", b =>
                {
                    b.HasOne("StageFlowVag.Domain.Entities.Blocos.Bloco", "Bloco")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("BlocoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageFlowVag.Domain.Entities.Solicitacoes.Solicitacao", "Solicitacao")
                        .WithMany()
                        .HasForeignKey("SolicitacaoId");

                    b.Navigation("Bloco");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Solicitacoes.Solicitacao", b =>
                {
                    b.HasOne("StageFlowVag.Domain.Entities.Blocos.Bloco", "Bloco")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("BlocoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StageFlowVag.Domain.Entities.Usuarios.Usuario", "Solicitante")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bloco");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Solicitacoes.SolicitacoesInsumos.SolicitacaoInsumo", b =>
                {
                    b.HasOne("StageFlowVag.Domain.Entities.Insumos.Insumo", "Insumo")
                        .WithMany("SolicitacaoInsumos")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageFlowVag.Domain.Entities.Solicitacoes.Solicitacao", "Solicitacao")
                        .WithMany("Insumos")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Blocos.Bloco", b =>
                {
                    b.Navigation("Disponibilidades");

                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Insumos.Insumo", b =>
                {
                    b.Navigation("SolicitacaoInsumos");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Solicitacoes.Solicitacao", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
