// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StageFlowVag.Repository;

#nullable disable

namespace StageFlowVag.Repository.Migrations
{
    [DbContext(typeof(StageFlowVagDbContext))]
    partial class StageFlowVagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StageFlowVag.Domain.Entities.AtendimentosDepartamentos.AtendimentoDepartamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<int>("Departamento")
                        .HasColumnType("integer")
                        .HasColumnName("departamento");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<int?>("ResponsavelId")
                        .HasColumnType("integer")
                        .HasColumnName("responsavel_id");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitacao_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Departamento")
                        .HasDatabaseName("idx_atendimento_departamento");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("SolicitacaoId")
                        .HasDatabaseName("idx_atendimento_solicitacao");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_atendimento_status");

                    b.ToTable("atendimento_departamento", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.ChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<DateTime?>("DataLimite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_limite");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer")
                        .HasColumnName("evento_id");

                    b.Property<bool>("GeradoAutomaticamente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("gerado_automaticamente");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ObservacoesConclusao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes_conclusao");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer")
                        .HasColumnName("prioridade");

                    b.Property<string>("ResponsavelNome")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("responsavel_nome");

                    b.Property<int>("SetorResponsavel")
                        .HasColumnType("integer")
                        .HasColumnName("setor_responsavel");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("DataLimite")
                        .HasDatabaseName("idx_checklist_data_limite");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("idx_checklist_evento");

                    b.HasIndex("SetorResponsavel")
                        .HasDatabaseName("idx_checklist_setor");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_checklist_status");

                    b.ToTable("checklist_item", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<int>("CoordenadorId")
                        .HasColumnType("integer")
                        .HasColumnName("coordenador_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CursoVinculado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("curso_vinculado");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("EmailCoordenador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_coordenador");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("local");

                    b.Property<string>("NomeCoordenador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_coordenador");

                    b.Property<string>("ObservacoesGerais")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observacoes_gerais");

                    b.Property<int>("PublicoEstimado")
                        .HasColumnType("integer")
                        .HasColumnName("publico_estimado");

                    b.Property<bool>("RequerCerimonial")
                        .HasColumnType("boolean")
                        .HasColumnName("requer_cerimonial");

                    b.Property<bool>("RequerDivulgacao")
                        .HasColumnType("boolean")
                        .HasColumnName("requer_divulgacao");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_evento");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CoordenadorId")
                        .HasDatabaseName("idx_eventos_coordenador");

                    b.HasIndex("DataInicio")
                        .HasDatabaseName("idx_eventos_data_inicio");

                    b.HasIndex("Local")
                        .HasDatabaseName("idx_eventos_local");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_eventos_status");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.RecursoAudioVisual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("NumeroPatrimonio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_patrimonio");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_disponivel");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("NumeroPatrimonio")
                        .HasDatabaseName("idx_recursos_patrimonio");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_recursos_status");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("idx_recursos_tipo");

                    b.ToTable("recurso_audiovisual", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.ReservaRecurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataHoraDevolucao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_devolucao");

                    b.Property<DateTime?>("DataHoraEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_entrega");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_fim");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer")
                        .HasColumnName("evento_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ObservacoesReserva")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes_reserva");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer")
                        .HasColumnName("recurso_id");

                    b.Property<string>("ResponsavelDevolucao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("responsavel_devolucao");

                    b.Property<string>("ResponsavelEntrega")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("responsavel_entrega");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("idx_reservas_evento");

                    b.HasIndex("RecursoId")
                        .HasDatabaseName("idx_reservas_recurso");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_reservas_status");

                    b.HasIndex("DataHoraInicio", "DataHoraFim")
                        .HasDatabaseName("idx_reservas_periodo");

                    b.ToTable("reserva_recurso", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Blocos.Bloco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("idx_blocos_nome");

                    b.ToTable("blocos", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Blocos.DisponibilidadeBloco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<int>("BlocoId")
                        .HasColumnType("integer")
                        .HasColumnName("bloco_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_fim");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_inicio");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<int?>("SolicitacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitacao_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BlocoId")
                        .HasDatabaseName("idx_disponibilidade_bloco");

                    b.HasIndex("SolicitacaoId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_disponibilidade_status");

                    b.HasIndex("DataHoraInicio", "DataHoraFim")
                        .HasDatabaseName("idx_disponibilidade_periodo");

                    b.ToTable("disponibilidade_blocos", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Insumos.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Departamento")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Solicitacoes.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<bool?>("Aprovado")
                        .HasColumnType("boolean")
                        .HasColumnName("aprovado");

                    b.Property<int?>("AprovadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("aprovado_por_id");

                    b.Property<int?>("BlocoId")
                        .HasColumnType("integer")
                        .HasColumnName("bloco_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_aprovacao");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_evento");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JustificativaRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("justificativa_rejeicao");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("local");

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_evento");

                    b.Property<int>("PublicoEstimado")
                        .HasColumnType("integer")
                        .HasColumnName("publico_estimado");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("integer")
                        .HasColumnName("solicitante_id");

                    b.HasKey("Id");

                    b.HasIndex("Aprovado")
                        .HasDatabaseName("idx_solicitacoes_aprovado");

                    b.HasIndex("BlocoId")
                        .HasDatabaseName("idx_solicitacoes_bloco");

                    b.HasIndex("DataEvento")
                        .HasDatabaseName("idx_solicitacoes_data");

                    b.HasIndex("SolicitanteId")
                        .HasDatabaseName("idx_solicitacoes_solicitante");

                    b.ToTable("solicitacoes", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Solicitacoes.SolicitacoesInsumos.SolicitacaoInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("SolicitacaoInsumos");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Departamento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matricula");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_usuarios_email");

                    b.HasIndex("Matricula")
                        .IsUnique()
                        .HasDatabaseName("idx_usuarios_matricula");

                    b.HasIndex("Role")
                        .HasDatabaseName("idx_usuarios_role");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.AtendimentosDepartamentos.AtendimentoDepartamento", b =>
                {
                    b.HasOne("StageFlowVag.Domain.Entities.Usuarios.Usuario", "Responsavel")
                        .WithMany("Atendimentos")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StageFlowVag.Domain.Entities.Solicitacoes.Solicitacao", "Solicitacao")
                        .WithMany("Atendimentos")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.ChecklistItem", b =>
                {
                    b.HasOne("StageFlowVag.Domain.Entities.Audiovisual.Evento", "Evento")
                        .WithMany("Checklist")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.ReservaRecurso", b =>
                {
                    b.HasOne("StageFlowVag.Domain.Entities.Audiovisual.Evento", "Evento")
                        .WithMany("RecursosReservados")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageFlowVag.Domain.Entities.Audiovisual.RecursoAudioVisual", "Recurso")
                        .WithMany("Reservas")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Blocos.DisponibilidadeBloco", b =>
                {
                    b.HasOne("StageFlowVag.Domain.Entities.Blocos.Bloco", "Bloco")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("BlocoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageFlowVag.Domain.Entities.Solicitacoes.Solicitacao", "Solicitacao")
                        .WithMany()
                        .HasForeignKey("SolicitacaoId");

                    b.Navigation("Bloco");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Solicitacoes.Solicitacao", b =>
                {
                    b.HasOne("StageFlowVag.Domain.Entities.Blocos.Bloco", "Bloco")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("BlocoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StageFlowVag.Domain.Entities.Usuarios.Usuario", "Solicitante")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bloco");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Solicitacoes.SolicitacoesInsumos.SolicitacaoInsumo", b =>
                {
                    b.HasOne("StageFlowVag.Domain.Entities.Insumos.Insumo", "Insumo")
                        .WithMany("SolicitacaoInsumos")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StageFlowVag.Domain.Entities.Solicitacoes.Solicitacao", "Solicitacao")
                        .WithMany("Insumos")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Solicitacao");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.Evento", b =>
                {
                    b.Navigation("Checklist");

                    b.Navigation("RecursosReservados");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Audiovisual.RecursoAudioVisual", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Blocos.Bloco", b =>
                {
                    b.Navigation("Disponibilidades");

                    b.Navigation("Solicitacoes");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Insumos.Insumo", b =>
                {
                    b.Navigation("SolicitacaoInsumos");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Solicitacoes.Solicitacao", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("StageFlowVag.Domain.Entities.Usuarios.Usuario", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
